services:
  mqtt:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    networks:
      - mqtt_lab

networks:
  mqtt_lab:
    name: testbed_mqtt_lab
    driver: bridge