services:

  mqtt:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    networks:
      - mqtt_lab

  mqtt-c1:
    image: eclipse-mosquitto:2
    ports:
      - "1884:1883"
    volumes:
      - ./config/mosquitto-c1.conf:/mosquitto/config/mosquitto.conf:ro
      - ./config/password_file:/mosquitto/config/password_file:ro
    networks:
      - mqtt_lab

  mqtt-c2:
    image: eclipse-mosquitto:2
    ports:
      - "8883:8883"
    volumes:
      - ./config/mosquitto-c2.conf:/mosquitto/config/mosquitto.conf:ro
      - ./config/password_file:/mosquitto/config/password_file:ro
      - ./config/certs/ca.crt:/mosquitto/config/certs/ca.crt:ro
      - ./config/certs/server.crt:/mosquitto/config/certs/server.crt:ro
      - ./config/certs/server.key:/mosquitto/config/certs/server.key:ro
    networks:
      - mqtt_lab

  netem-proxy:
    build:
      context: ./network
    container_name: testbed-netem-proxy
    cap_add:
      - NET_ADMIN
    depends_on:
      - mqtt
      - mqtt-c1
      - mqtt-c2
    ports:
      - "2883:1883"
      - "2884:1884"
      - "9883:8883"
      - "14840:14840"
      - "14841:14841"
      - "14842:14842"
    networks:
      - mqtt_lab

networks:
  mqtt_lab:
    name: testbed_mqtt_lab
    driver: bridge