listener 8883 0.0.0.0
allow_anonymous false

password_file /etc/mosquitto/passwd-fair-v1

certfile /etc/mosquitto/certs/fair-v1-c2/server.crt
keyfile /etc/mosquitto/certs/fair-v1-c2/server.key

tls_version tlsv1.2
require_certificate false
